spring:
  redis:
    host: 127.0.0.1
    database: 1
  datasource:
    url: jdbc:mysql://localhost:3306/shortUrl?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: qwe123
    driver-class-name: com.mysql.cj.jdbc.Driver

huaixia:
  url: http://127.0.0.1:8080/


